### ISSUE TITLE
Compatability with Browser environments - move to WebCryptoAPI

### ISSUE THREAD

**Issue by ghost** [iris-connect/IRIS-library-js#4]
The IRIS-library throws an exception in ReactJS. As i understand the library is not intendent for usual Browsers. Are there some plans in the future that couldt include this possibility? 

Exception 
TypeError: Cannot set property 'crypto' of undefined

**Comment by BerniWittmann** [comment]
@Dimitrj Thanks for bringing this up. 
It 100% makes sense to make this available in Browser environments, since this allows to really e2e encrypt the data. 
The current codebase was made during a hackathon (https://updatedeutschland.org/), so for the quick use case it was made to work in a node environment. 

I will rewrite the `crypto.ts` helper functions to use the WebCryptoAPI instead of the node crypto module to allow support for browser environments. Anyways, the encryption process needs some rework due to some changes in the server API and how it expects the data to be encrypted. Sadly, I do not have the details yet (@hey-johnnypark), but i will make those changes as soon as i get them :)

**Comment by BerniWittmann** [comment]
@Dimitrj I refactored the library to use the WebCryptoAPI instead of node crypto, so you should be able to go ahead and use it in your React application
